# -*- coding: utf-8 -*-
"""Copy of Copy of Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12uaSZUX4iFymrPsTc5aph6sYnqsg049Z
"""

1) Python?
 Python is an interpreted, object-oriented, high-level programming language with dynamic semantics developed by Guido van Rossum.
 It was originally released in 1991. Designed to be easy as well as fun, the name "Python" is a nod to the British comedy group Monty Python.
 Python has a reputation as a beginner-friendly language, replacing Java as the most widely used introductory language
 because it handles much of the complexity for the user, allowing beginners to focus on fully grasping programming concepts rather than minute details.
 Python is used for server-side web development, software development, mathematics, and system scripting, and is popular for Rapid Application Development
and as a scripting or glue language to tie existing components because of its high-level, built-in data structures, dynamic typing, and dynamic binding.

2)create a login function.
print('Create User')
User_Name = input('Create User_Name\n')
Password = input('Create Password\n')
Enter_User = input('Enter User Name\n')
Enter_Password=input('Enter the Password\n')
if User_Name == Enter_User and Password == Enter_Password:
    print("Successfully Login")
else:
    print('Incorrect Username or Password')

print('Find the odd or Even')
Type_Number = int(input('Enter the number\n'))
if Type_Number % 2 == 0:
 print("its even number")
else:
     print("its odd number")

4) Create a list of fruits and iterate through them

print('List of Fruits')
Fruits={'banana','starfruit','mango','pears','banana','apple','jackfruit','watermelon'}
for x in Fruits:
    print(x)